language: generic 
git:
  depth: 3
deploy:
  provider: pages
  edge: true,
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  commit_messages: "release: Deploy"
  on: 
    branch: main
notifications:
  email:
    on_success: never
    on_failure: always